// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSite.DAL;

namespace WebSite.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20190910145842_Initial8")]
    partial class Initial8
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebSite.DAL.Models.category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            name = "Clothing"
                        },
                        new
                        {
                            ID = 2,
                            name = "Electronics"
                        },
                        new
                        {
                            ID = 3,
                            name = "Kitchen"
                        },
                        new
                        {
                            ID = 4,
                            name = "Misc"
                        });
                });

            modelBuilder.Entity("WebSite.DAL.Models.item", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("categoryID");

                    b.Property<string>("name")
                        .IsRequired();

                    b.Property<int>("value");

                    b.HasKey("ID");

                    b.HasIndex("categoryID");

                    b.ToTable("items");
                });

            modelBuilder.Entity("WebSite.DAL.Models.item", b =>
                {
                    b.HasOne("WebSite.DAL.Models.category", "category")
                        .WithMany()
                        .HasForeignKey("categoryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
